# This docker-compose.yml file is intended for development support. It
# is *not* meant for production.

version: '3.8'
services:
  meteor_app:
    build:
      context: .
    ports:
      - 443:3000
