# This docker-compose file is meant to be used on atari.epfl.ch (prod)
# or on atari-test.epfl.ch (staging)

services:
  meteor:
    container_name: atari-meteor
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - ATARI_ENVIRONMENT=${ATARI_ENVIRONMENT:-prod}
      - ATARI_DEBUG=${ATARI_DEBUG:-0}
  traefik:
    container_name: atari-traefik
    image: traefik:v2.10
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/traefik:/etc/traefik
