# This docker-compose.yml file is intended for development support. It
# is *not* meant for production.
services:
  # meteor_app:
  #   build:
  #     context: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/usr/src/app

  # Keycloak is an OpenID-Connect IdP (Identity Provider) that is easy
  # to set up. It mocks out that feature in the react-starter-kit application,
  # allowing testing with arbitrary users and groups. See further
  # details on the startup sequence of Keycloak (and the
  # --import-realm flag) in ./keycloak/README.md
  keycloak:
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: mariadb
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      # Since the Keycloak password is easy to guess, opening up this
      # port further than localhost is *not* recommended.
      - "127.0.0.1:8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      # Please run:
      # cd keycloak/themes; git clone git@github.com:epfl-si/keycloak.theme-login-epfl.git EPFL
      # to install the EPFL theme.
      - ./keycloak/themes:/opt/keycloak/themes
  # MariaDB is used by Keycloak for persistence. The react-starter-kit application
  # itself uses sqlite in development (which unfortunately, is not an
  # option for Keycloak at the moment).
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - ./keycloak/initdb.d:/docker-entrypoint-initdb.d
volumes:
  mariadb: {}
