export interface UnitInfos {
  fonction: string,
  libelle: string,
  adresse_1?: string,
  adresse_2?: string,
  adresse_3?: string,
  adresse_4?: string,
  phone_numbers?: string[],
  office?: string,
  mainOffice?: string,
  website?: string,
  unit: string,
  statut: string,
  hierarchie: string,
}
